version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - api
      - db
      - redis
      - registry
      - example-agent
    environment:
      - TEST_DATABASE_URL=postgresql://postgres:postgres@db:5432/test_autonomoussphere
      - REGISTRY_URL=http://registry:8081
      - REDIS_URL=redis://redis:6379/0
    networks:
      - autonomoussphere-network
    volumes:
      - ./tests:/app/tests
      - ./test-results:/app/test-results

networks:
  autonomoussphere-network:
    external: true